/**
 * Fix Generator — produces minimal code patches for analyzed build errors.
 * Priority order:
 *   1. Repair memory (instant, no AI cost)
 *   2. Deterministic regex fixes
 *   3. AI-generated fix (last resort)
 */

import { aiRequest, stripFences } from '@/lib/core/ai-request'
import { logger } from '@/lib/core/logger'
import { repairMemory, normalizeError } from './repair-memory'
import type { FixTransform } from './repair-memory'
import type { AnalyzedError } from './error-analyzer'
import type { ModelId } from '@/lib/ai-engine/model-router'

export interface CodeFix {
  /** The file path to patch */
  file: string
  /** The full updated file content (not a diff — always full replacement) */
  updatedContent: string
  /** Short description of what was changed */
  description: string
  /** Whether this fix was generated by AI, deterministically, or from memory */
  source: 'deterministic' | 'ai' | 'memory'
  /** The normalized pattern key (used to update memory after rebuild) */
  memoryPattern?: string
}

// ── Deterministic fixers ──────────────────────────────────────────────────────

/** Add `export` keyword to a bare function/class/const declaration */
function fixMissingExport(source: string, symbolName: string): string {
  // Already exported — nothing to do
  if (new RegExp(`export\\s+(?:async\\s+)?(?:function|const|class|interface|type)\\s+${symbolName}\\b`).test(source)) {
    return source
  }
  // export default function Foo → export function Foo
  source = source.replace(
    new RegExp(`export\\s+default\\s+function\\s+${symbolName}\\b`),
    `export function ${symbolName}`,
  )
  source = source.replace(
    new RegExp(`export\\s+default\\s+class\\s+${symbolName}\\b`),
    `export class ${symbolName}`,
  )
  // bare function Foo
  source = source.replace(
    new RegExp(`(^|\\n)([ \\t]*)(async\\s+)?function\\s+(${symbolName})\\b`),
    (_, pre, indent, asyncKw, name) => `${pre}${indent}export ${asyncKw ?? ''}function ${name}`,
  )
  // bare class Foo
  source = source.replace(
    new RegExp(`(^|\\n)([ \\t]*)class\\s+(${symbolName})\\b`),
    (_, pre, indent, name) => `${pre}${indent}export class ${name}`,
  )
  // bare const Foo =
  source = source.replace(
    new RegExp(`(^|\\n)([ \\t]*)const\\s+(${symbolName})\\s*=`),
    (_, pre, indent, name) => `${pre}${indent}export const ${name} =`,
  )
  return source
}

/** Convert `export default function` → `export function` (for named import compatibility) */
function fixDefaultToNamed(source: string): string {
  source = source.replace(/export\s+default\s+function\s+(\w+)/g, 'export function $1')
  source = source.replace(/export\s+default\s+class\s+(\w+)/g, 'export class $1')
  return source
}

/** Extract the symbol name from a missing-export error message */
function extractSymbolName(message: string): string | null {
  const m =
    message.match(/Export '(\w+)' doesn't exist/i) ??
    message.match(/does not provide an export named '(\w+)'/i) ??
    message.match(/named export '(\w+)'/i)
  return m?.[1] ?? null
}

// ── AI-powered fixer ──────────────────────────────────────────────────────────

const FIX_SYSTEM = `You are an expert TypeScript/React engineer.
You will receive a build error message and the current file content.
Your job is to return the COMPLETE fixed file content — no explanations, no markdown fences.
Rules:
- Fix ONLY the reported error. Do not refactor unrelated code.
- Preserve all existing functionality.
- Never modify authentication, payment, or database schema logic.
- Return the full file content, ready to save directly to disk.`

async function aiGenerateFix(
  error: AnalyzedError,
  fileContent: string,
  modelId: ModelId,
): Promise<string> {
  const prompt = `Build error in file: ${error.targetFile}

Error message:
${error.original.message}

Error category: ${error.category}
Description: ${error.description}

Current file content:
\`\`\`
${fileContent.slice(0, 6000)}
\`\`\`

Return the complete fixed file content only.`

  const result = await aiRequest({
    system: FIX_SYSTEM,
    prompt,
    modelId,
    maxOutputTokens: 8000,
    timeoutMs: 30_000,
  })
  return stripFences(result)
}

// ── Main fix generator ────────────────────────────────────────────────────────

export async function generateFix(
  error: AnalyzedError,
  files: Record<string, string>,
  modelId: ModelId = 'gemini_flash',
): Promise<CodeFix | null> {
  const { targetFile, strategy } = error
  if (!targetFile) {
    logger.warn('system', 'Cannot generate fix — no target file', error.original.message)
    return null
  }

  // Normalize path: strip leading ./ or /
  const normalizedPath = targetFile.replace(/^\.\//, '').replace(/^\//, '')
  const fileContent = files[normalizedPath] ?? files[targetFile] ?? ''

  if (!fileContent && strategy !== 'add-import') {
    logger.warn('system', `File not in project files: ${targetFile}`)
    return null
  }

  // Compute the normalized pattern for memory lookup
  const memoryPattern = normalizeError(error.original.message, error.category)

  try {
    // ── 1. Repair memory lookup ──────────────────────────────────────────────
    const memorized = repairMemory.getFix(memoryPattern)
    if (memorized) {
      const applied = applyTransform(fileContent, memorized.fix)
      if (applied !== null && applied !== fileContent) {
        repairMemory.incrementUsage(memoryPattern)
        return {
          file: normalizedPath,
          updatedContent: applied,
          description: `Memory fix: ${memorized.fix.type} (used ${memorized.usageCount + 1}x)`,
          source: 'memory',
          memoryPattern,
        }
      }
    }

    // ── 2. Deterministic fixes ───────────────────────────────────────────────
    if (strategy === 'add-named-export') {
      const symbol = extractSymbolName(error.original.message)
      if (symbol) {
        const fixed = fixMissingExport(fileContent, symbol)
        if (fixed !== fileContent) {
          const transform: FixTransform = { type: 'add-named-export', symbolName: symbol }
          repairMemory.saveFix(memoryPattern, transform, error.category, strategy)
          return { file: normalizedPath, updatedContent: fixed, description: `Added named export for "${symbol}"`, source: 'deterministic', memoryPattern }
        }
      }
    }

    if (strategy === 'convert-default-export') {
      const fixed = fixDefaultToNamed(fileContent)
      if (fixed !== fileContent) {
        const transform: FixTransform = { type: 'convert-default-export' }
        repairMemory.saveFix(memoryPattern, transform, error.category, strategy)
        return { file: normalizedPath, updatedContent: fixed, description: 'Converted default export to named export', source: 'deterministic', memoryPattern }
      }
    }

    // ── 3. AI-powered fix ────────────────────────────────────────────────────
    logger.info('system', `Using AI to fix: ${error.category} in ${targetFile}`)
    const fixed = await aiGenerateFix(error, fileContent, modelId)
    if (fixed && fixed !== fileContent) {
      // Store as full-replacement — will be used for identical files only
      const transform: FixTransform = { type: 'full-replacement', content: fixed }
      repairMemory.saveFix(memoryPattern, transform, error.category, strategy)
      return { file: normalizedPath, updatedContent: fixed, description: `AI-repaired: ${error.category}`, source: 'ai', memoryPattern }
    }

    logger.warn('system', `Fix generator produced no change for ${targetFile}`)
    return null
  } catch (err) {
    logger.error('system', `Fix generation failed for ${targetFile}`, err instanceof Error ? err.message : String(err))
    return null
  }
}

// ── Apply a stored FixTransform to file content ───────────────────────────────

function applyTransform(fileContent: string, transform: FixTransform): string | null {
  switch (transform.type) {
    case 'add-named-export':
      return fixMissingExport(fileContent, transform.symbolName)
    case 'convert-default-export':
      return fixDefaultToNamed(fileContent)
    case 'add-import':
      // Only add if not already present
      if (fileContent.includes(transform.importStatement)) return null
      return `${transform.importStatement}\n${fileContent}`
    case 'full-replacement':
      // Full replacements are file-specific — getFix() already filters these out
      return null
    default:
      return null
  }
}
