const SPECS = [
  { label: 'Frontend', value: 'Next.js 14 App Router + TypeScript + Tailwind CSS' },
  { label: 'Backend', value: 'Next.js API Routes with automatic REST generation' },
  { label: 'Database', value: 'Prisma ORM with PostgreSQL schema auto-generation' },
  { label: 'Auth', value: 'Clerk authentication with middleware protection' },
  { label: 'Repair', value: 'AI repair agent — detects and fixes build errors automatically' },
  { label: 'Deployment', value: 'Vercel & Netlify with CI/CD and custom domains' },
]

const EXAMPLE_APPS = [
  { name: 'FlowCRM', type: 'CRM', desc: 'Contact management, deal pipeline, analytics', color: 'from-violet-500 to-indigo-600', emoji: '📊' },
  { name: 'BookEasy', type: 'Booking', desc: 'Appointment scheduling with calendar sync', color: 'from-cyan-500 to-blue-600', emoji: '📅' },
  { name: 'TaskFlow', type: 'Project Mgmt', desc: 'Kanban boards, sprints, team collaboration', color: 'from-emerald-500 to-teal-600', emoji: '✅' },
  { name: 'InvoiceAI', type: 'Invoicing', desc: 'Invoice generation, payment tracking, PDF export', color: 'from-amber-500 to-orange-600', emoji: '💰' },
  { name: 'LearnHub', type: 'LMS', desc: 'Course creation, video lessons, progress tracking', color: 'from-pink-500 to-rose-600', emoji: '🎓' },
  { name: 'ShopForge', type: 'E-Commerce', desc: 'Product catalog, cart, checkout, inventory', color: 'from-orange-500 to-red-600', emoji: '🛍️' },
]

export function ProductDemo() {
  return (
    <>
      {/* Platform Specs */}
      <section className="py-24 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <div className="grid grid-cols-1 gap-12 lg:grid-cols-2 items-center">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-slate-50 px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:border-white/10 dark:bg-white/5 dark:text-slate-400 mb-5">
                Platform Specifications
              </div>
              <h2 className="text-4xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-5xl mb-5">
                Production-grade code,
                <br />
                <span className="bg-gradient-to-r from-violet-600 to-cyan-500 bg-clip-text text-transparent dark:from-violet-400 dark:to-cyan-400">
                  every single time
                </span>
              </h2>
              <p className="text-lg text-slate-500 dark:text-slate-400 mb-8">
                BuildForge doesn&apos;t generate toy apps. Every project uses the same stack top engineers use — with proper types, error handling, and deployment configs.
              </p>
              <div className="space-y-3">
                {SPECS.map((s) => (
                  <div key={s.label} className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-3.5 dark:border-white/8 dark:bg-white/3">
                    <span className="mt-0.5 shrink-0 rounded-md bg-violet-100 px-2 py-0.5 text-[10px] font-bold text-violet-700 dark:bg-violet-500/20 dark:text-violet-300">
                      {s.label}
                    </span>
                    <span className="text-sm text-slate-600 dark:text-slate-300">{s.value}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Code block */}
            <div className="rounded-2xl border border-slate-200 bg-[#0d0d18] overflow-hidden shadow-2xl dark:border-white/8">
              <div className="flex items-center gap-2 border-b border-white/6 bg-[#0a0a14] px-4 py-3">
                <div className="flex gap-1.5">
                  <div className="h-3 w-3 rounded-full bg-red-400" />
                  <div className="h-3 w-3 rounded-full bg-yellow-400" />
                  <div className="h-3 w-3 rounded-full bg-green-400" />
                </div>
                <span className="text-[11px] text-white/30 ml-2">prisma/schema.prisma — auto-generated</span>
              </div>
              <pre className="p-5 text-[11px] leading-relaxed overflow-x-auto">
                <code>
                  <span className="text-white/30">{'// Generated by BuildForge AI\n'}</span>
                  <span className="text-violet-400">{'model '}</span>
                  <span className="text-cyan-300">{'Contact '}</span>
                  <span className="text-white/60">{'{\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'id'}</span>
                  <span className="text-white/40">{'        String   '}</span>
                  <span className="text-violet-400">{'@id @default'}</span>
                  <span className="text-white/60">{'(cuid())\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'email'}</span>
                  <span className="text-white/40">{'     String   '}</span>
                  <span className="text-violet-400">{'@unique\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'name'}</span>
                  <span className="text-white/40">{'      String\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'company'}</span>
                  <span className="text-white/40">{'   String?\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'deals'}</span>
                  <span className="text-white/40">{'     Deal[]\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'createdAt'}</span>
                  <span className="text-white/40">{'  DateTime  '}</span>
                  <span className="text-violet-400">{'@default'}</span>
                  <span className="text-white/60">{'(now())\n'}</span>
                  <span className="text-white/60">{'}\n\n'}</span>
                  <span className="text-violet-400">{'model '}</span>
                  <span className="text-cyan-300">{'Deal '}</span>
                  <span className="text-white/60">{'{\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'id'}</span>
                  <span className="text-white/40">{'        String   '}</span>
                  <span className="text-violet-400">{'@id @default'}</span>
                  <span className="text-white/60">{'(cuid())\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'title'}</span>
                  <span className="text-white/40">{'     String\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'value'}</span>
                  <span className="text-white/40">{'     Float\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'status'}</span>
                  <span className="text-white/40">{'    DealStatus\n'}</span>
                  <span className="text-white/40">{'  '}</span>
                  <span className="text-emerald-300">{'contact'}</span>
                  <span className="text-white/40">{'   Contact  '}</span>
                  <span className="text-violet-400">{'@relation'}</span>
                  <span className="text-white/60">{'(...)\n'}</span>
                  <span className="text-white/60">{'}'}</span>
                </code>
              </pre>
            </div>
          </div>
        </div>
      </section>

      {/* Example Apps */}
      <section className="py-24 px-4 sm:px-6 lg:px-8 bg-slate-50/50 dark:bg-white/[0.01]">
        <div className="mx-auto max-w-7xl">
          <div className="text-center mb-14">
            <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-1.5 text-xs font-semibold uppercase tracking-wider text-slate-500 dark:border-white/10 dark:bg-white/5 dark:text-slate-400 mb-4">
              Example Apps
            </div>
            <h2 className="text-4xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-5xl">
              SaaS apps built with BuildForge
            </h2>
            <p className="mt-4 text-lg text-slate-500 dark:text-slate-400">
              Every app is a full-stack Next.js project with auth, database, and deployment — generated in minutes.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {EXAMPLE_APPS.map((app) => (
              <div
                key={app.name}
                className="group rounded-2xl border border-slate-200 bg-white p-5 transition-all hover:-translate-y-1 hover:shadow-xl dark:border-white/8 dark:bg-white/3"
              >
                <div className={`mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br ${app.color} text-2xl shadow-lg`}>
                  {app.emoji}
                </div>
                <div className="flex items-center gap-2 mb-1">
                  <h3 className="text-base font-semibold text-slate-900 dark:text-white">{app.name}</h3>
                  <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-semibold text-slate-500 dark:bg-white/10 dark:text-slate-400">
                    {app.type}
                  </span>
                </div>
                <p className="text-sm text-slate-500 dark:text-slate-400">{app.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
