import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy | BuildForge AI',
  description: 'BuildForge AI Privacy Policy. Learn how we collect, use, and protect your personal data.',
  alternates: { canonical: 'https://buildforge.ai/legal/privacy' },
}

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-20 prose prose-neutral dark:prose-invert">
      <h1>Privacy Policy</h1>
      <p className="text-muted-foreground">Last updated: March 1, 2026</p>

      <h2>1. Information We Collect</h2>
      <p>
        We collect information you provide when creating an account, including your name, email address,
        and payment information. We also collect usage data such as projects created, prompts submitted,
        and features used to improve the platform.
      </p>

      <h2>2. How We Use Your Information</h2>
      <p>We use your information to:</p>
      <ul>
        <li>Provide and improve the BuildForge AI platform</li>
        <li>Process payments and manage your subscription</li>
        <li>Send product updates and important account notifications</li>
        <li>Analyze usage patterns to improve AI generation quality</li>
      </ul>

      <h2>3. Data Storage and Security</h2>
      <p>
        Your data is stored securely using industry-standard encryption. We use Supabase (PostgreSQL)
        for database storage and Clerk for authentication. Payment data is handled by Stripe and never
        stored on our servers.
      </p>

      <h2>4. Your Generated Content</h2>
      <p>
        You own all code and content generated by BuildForge AI. We do not claim ownership of your
        projects. We may use anonymized, aggregated generation data to improve our AI models.
      </p>

      <h2>5. Third-Party Services</h2>
      <p>
        BuildForge uses Clerk (authentication), Stripe (payments), and Vercel (hosting). Each service
        has its own privacy policy governing their data practices.
      </p>

      <h2>6. Contact</h2>
      <p>
        For privacy-related questions, contact us at privacy@buildforge.ai.
      </p>
    </main>
  )
}
