import { auth } from '@clerk/nextjs/server'
import { db } from '@/lib/db'
import { NextResponse } from 'next/server'
import { z } from 'zod'
import { enforceCredits } from '@/lib/credits-server'

const schema = z.object({
  projectId: z.string(),
  repoName: z.string().min(1).max(100).regex(/^[a-zA-Z0-9_.-]+$/),
  isPrivate: z.boolean().default(false),
  files: z.record(z.string()),
})

async function githubRequest(
  path: string,
  token: string,
  method = 'GET',
  body?: unknown
) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body ? JSON.stringify(body) : undefined,
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data.message ?? `GitHub API error ${res.status}`)
  return data
}

export async function POST(req: Request) {
  const { userId } = await auth()
  if (!userId) return new NextResponse('Unauthorized', { status: 401 })

  const user = await db.user.findUnique({ where: { clerkId: userId } })
  if (!user) return new NextResponse('User not found', { status: 404 })

  const githubToken = user.githubToken
  if (!githubToken) {
    return NextResponse.json(
      { error: 'GitHub not connected. Add your GitHub token in Settings.' },
      { status: 400 }
    )
  }

  const body = await req.json()
  const parsed = schema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 })
  }

  const { projectId, repoName, isPrivate, files } = parsed.data

  const project = await db.project.findFirst({
    where: { id: projectId, userId: user.id },
  })
  if (!project) return new NextResponse('Project not found', { status: 404 })

  // Enforce credits
  const creditError = await enforceCredits(userId, 'githubExport', { projectId, repoName })
  if (creditError) return NextResponse.json({ error: creditError }, { status: 402 })

  try {
    // 1. Get authenticated user info
    const ghUser = await githubRequest('/user', githubToken)

    // 2. Create repository
    const repo = await githubRequest('/user/repos', githubToken, 'POST', {
      name: repoName,
      description: `Generated by BuildForge AI — ${project.name}`,
      private: isPrivate,
      auto_init: false,
    })

    const owner = ghUser.login
    const repoFullName = repo.full_name

    // 3. Push all files via Git Trees API (single commit)
    // First create blobs for each file
    const blobs = await Promise.all(
      Object.entries(files).map(async ([path, content]) => {
        const blob = await githubRequest(
          `/repos/${repoFullName}/git/blobs`,
          githubToken,
          'POST',
          { content: Buffer.from(content).toString('base64'), encoding: 'base64' }
        )
        return { path, sha: blob.sha }
      })
    )

    // Create tree
    const tree = await githubRequest(
      `/repos/${repoFullName}/git/trees`,
      githubToken,
      'POST',
      {
        tree: blobs.map(b => ({
          path: b.path,
          mode: '100644',
          type: 'blob',
          sha: b.sha,
        })),
      }
    )

    // Create commit
    const commit = await githubRequest(
      `/repos/${repoFullName}/git/commits`,
      githubToken,
      'POST',
      {
        message: `Initial commit — generated by BuildForge AI`,
        tree: tree.sha,
        parents: [],
      }
    )

    // Update HEAD ref
    await githubRequest(
      `/repos/${repoFullName}/git/refs`,
      githubToken,
      'POST',
      { ref: 'refs/heads/main', sha: commit.sha }
    )

    // Save repo URL to project
    await db.project.update({
      where: { id: projectId },
      data: { githubRepo: repo.html_url },
    })

    return NextResponse.json({
      repoUrl: repo.html_url,
      cloneUrl: repo.clone_url,
      owner,
      repo: repoName,
    })
  } catch (err) {
    console.error('GitHub export error:', err)
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'GitHub export failed' },
      { status: 500 }
    )
  }
}
