import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Generate Websites with AI — Instant AI Website Generation | BuildForge',
  description: 'Generate beautiful, SEO-optimized websites with AI. BuildForge creates complete websites from a text prompt — no design or coding skills needed.',
  keywords: ['generate websites with AI', 'AI website generator', 'create website automatically', 'AI web builder'],
  alternates: { canonical: 'https://buildforge.ai/solutions/generate-websites-with-ai' },
}

export default function GenerateWebsitesWithAIPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-20">
      <h1 className="text-4xl font-bold mb-4">Generate Websites with AI</h1>
      <p className="text-xl text-muted-foreground mb-10">
        Describe your website and BuildForge AI generates it — complete with design, content, SEO
        metadata, and deployment. From prompt to live site in under 5 minutes.
      </p>

      <h2 className="text-2xl font-semibold mb-4">AI Website Generation That Actually Works</h2>
      <p className="text-muted-foreground mb-6">
        Most AI website builders produce generic templates. BuildForge generates custom, production-quality
        websites tailored to your specific business, brand, and goals. Every site includes proper SEO
        structure, responsive design, and clean code you can own.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Types of Websites You Can Generate</h2>
      <ul className="space-y-2 text-muted-foreground mb-8 list-disc list-inside">
        <li>SaaS landing pages and marketing sites</li>
        <li>Portfolio and personal brand websites</li>
        <li>Product showcase and e-commerce pages</li>
        <li>Agency and service business websites</li>
        <li>Blog and content platforms</li>
        <li>Event and conference pages</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">SEO Built In</h2>
      <p className="text-muted-foreground mb-8">
        Every website generated by BuildForge includes proper H1/H2 structure, meta titles, meta
        descriptions, Open Graph tags, canonical URLs, and JSON-LD structured data — so your site
        ranks from day one.
      </p>

      <Link href="/signup" className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-colors">
        Generate Your Website
      </Link>
    </main>
  )
}
