import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Build Dashboards with AI — Generate Analytics Dashboards Instantly | BuildForge',
  description: 'Generate beautiful analytics dashboards, reporting tools, and data visualization apps with AI. BuildForge creates complete dashboard applications from a prompt.',
  keywords: ['build dashboards with AI', 'AI dashboard generator', 'generate analytics dashboard', 'AI data visualization'],
  alternates: { canonical: 'https://buildforge.ai/use-cases/build-dashboards' },
}

export default function BuildDashboardsPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-20">
      <h1 className="text-4xl font-bold mb-4">Build Dashboards with AI</h1>
      <p className="text-xl text-muted-foreground mb-10">
        Generate complete analytics dashboards and data visualization apps from a description.
        BuildForge creates production-ready dashboards with charts, tables, and real-time data.
      </p>

      <h2 className="text-2xl font-semibold mb-4">Dashboard Types</h2>
      <ul className="space-y-2 text-muted-foreground mb-8 list-disc list-inside">
        <li>SaaS analytics and user metrics dashboards</li>
        <li>Business intelligence and KPI reporting</li>
        <li>Marketing performance dashboards</li>
        <li>Financial reporting and revenue analytics</li>
        <li>Operations and logistics monitoring</li>
        <li>Customer success and support dashboards</li>
      </ul>

      <h2 className="text-2xl font-semibold mb-4">Charts, Tables, and Real-Time Data</h2>
      <p className="text-muted-foreground mb-8">
        Every dashboard generated by BuildForge includes interactive charts, sortable data tables,
        date range filters, and export functionality — all wired up to your data source automatically.
      </p>

      <Link href="/signup" className="inline-block bg-primary text-primary-foreground px-6 py-3 rounded-lg font-semibold hover:bg-primary/90 transition-colors">
        Build Your Dashboard
      </Link>
    </main>
  )
}
