// AI Router — selects the generation backend based on AI_PROVIDER env var
// Supported providers: ollama | gemini | openai | auto (default)
//
// Usage:
//   const result = await generateCode(prompt, { system, appType })
//   result.files  — Record<string, string>
//   result.text   — raw AI response
//   result.provider — which provider was used

import { generateWithOllama, buildOllamaAppPrompt } from './ollama'
import { parseAIOutput, detectEntrypoint } from './file-parser'
import { builderSystemPrompt, buildUserMessage, detectAppType } from '@/lib/ai-engine/agents/builder-agent'

export type AIProvider = 'ollama' | 'gemini' | 'openai' | 'auto'

export interface GenerateCodeOptions {
  system?: string
  appType?: string
  existingFiles?: Record<string, string>
  model?: string
  maxTokens?: number
}

export interface GenerateCodeResult {
  text: string
  files: Record<string, string>
  entrypoint: string
  description: string
  provider: AIProvider
  model: string
}

function getConfiguredProvider(): AIProvider {
  const p = (process.env.AI_PROVIDER ?? 'auto').toLowerCase() as AIProvider
  return ['ollama', 'gemini', 'openai', 'auto'].includes(p) ? p : 'auto'
}

/**
 * Generate code using the configured AI provider.
 * Falls back through: ollama → gemini → openai
 */
export async function generateCode(
  prompt: string,
  options: GenerateCodeOptions = {}
): Promise<GenerateCodeResult> {
  const provider = getConfiguredProvider()
  const appType = options.appType ?? detectAppType(prompt)

  // Build system + user messages using the existing builder-agent prompts
  const system = options.system ?? builderSystemPrompt(appType, options.existingFiles, prompt)
  const userMsg = buildUserMessage(prompt, appType, options.existingFiles)

  if (provider === 'ollama' || provider === 'auto') {
    const result = await tryOllama(prompt, system, userMsg, appType, options)
    if (result) return result
    // auto falls through to cloud
    if (provider === 'ollama') {
      throw new Error('Ollama is not available. Make sure Ollama is running at ' + (process.env.OLLAMA_BASE_URL ?? 'http://localhost:11434'))
    }
  }

  if (provider === 'gemini' || provider === 'auto') {
    const result = await tryGemini(system, userMsg, appType, options)
    if (result) return result
    if (provider === 'gemini') throw new Error('Gemini API failed. Check your GEMINI_API_KEY.')
  }

  if (provider === 'openai' || provider === 'auto') {
    const result = await tryOpenAI(system, userMsg, appType, options)
    if (result) return result
  }

  throw new Error('All AI providers failed. Check your configuration.')
}

async function tryOllama(
  rawPrompt: string,
  system: string,
  userMsg: string,
  appType: string,
  options: GenerateCodeOptions
): Promise<GenerateCodeResult | null> {
  try {
    const { isOllamaAvailable } = await import('./ollama')
    const available = await isOllamaAvailable()
    if (!available) return null

    const model = options.model ?? process.env.OLLAMA_MODEL ?? 'qwen2.5-coder'

    // Use the structured FILE: block prompt for Ollama (better for local models)
    const ollamaPrompt = buildOllamaAppPrompt(rawPrompt, appType)
    const fullPrompt = `${system}\n\n${ollamaPrompt}`

    const text = await generateWithOllama(fullPrompt, {
      model,
      maxTokens: options.maxTokens ?? 12000,
    })

    if (!text) return null

    // Try to parse as JSON first (if model follows the system prompt format)
    // then fall back to FILE: block parsing
    const files = parseAIOutput(text) ?? parseAIOutput(userMsg + '\n' + text)
    if (!files || Object.keys(files).length === 0) return null

    const entrypoint = detectEntrypoint(files)
    return {
      text,
      files,
      entrypoint,
      description: `Generated by Ollama (${model})`,
      provider: 'ollama',
      model,
    }
  } catch (err) {
    console.warn('[ai-router] Ollama failed:', err)
    return null
  }
}

async function tryGemini(
  system: string,
  userMsg: string,
  appType: string,
  options: GenerateCodeOptions
): Promise<GenerateCodeResult | null> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) return null
  try {
    const modelName = 'gemini-1.5-flash'
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`
    const res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        system_instruction: { parts: [{ text: system }] },
        contents: [{ role: 'user', parts: [{ text: userMsg }] }],
        generationConfig: { maxOutputTokens: options.maxTokens ?? 12000, temperature: 0.2 },
      }),
    })
    if (!res.ok) return null
    const data = await res.json() as { candidates?: { content: { parts: { text: string }[] } }[] }
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text ?? ''
    if (!text) return null
    const files = parseAIOutput(text)
    if (!files || Object.keys(files).length === 0) return null
    const entrypoint = detectEntrypoint(files)
    return { text, files, entrypoint, description: `Generated by Gemini Flash`, provider: 'gemini', model: modelName }
  } catch (err) {
    console.warn('[ai-router] Gemini failed:', err)
    return null
  }
}

async function tryOpenAI(
  system: string,
  userMsg: string,
  appType: string,
  options: GenerateCodeOptions
): Promise<GenerateCodeResult | null> {
  const apiKey = process.env.OPENAI_API_KEY
  if (!apiKey) return null
  try {
    const model = 'gpt-4o-mini'
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
      body: JSON.stringify({
        model,
        messages: [{ role: 'system', content: system }, { role: 'user', content: userMsg }],
        max_tokens: options.maxTokens ?? 12000,
        temperature: 0.2,
      }),
    })
    if (!res.ok) return null
    const data = await res.json() as { choices?: { message: { content: string } }[] }
    const text = data.choices?.[0]?.message?.content ?? ''
    if (!text) return null
    const files = parseAIOutput(text)
    if (!files || Object.keys(files).length === 0) return null
    const entrypoint = detectEntrypoint(files)
    return { text, files, entrypoint, description: `Generated by OpenAI ${model}`, provider: 'openai', model }
  } catch (err) {
    console.warn('[ai-router] OpenAI failed:', err)
    return null
  }
}
