// Server-safe marketplace data (no localStorage, no browser APIs)
// Used by the API route to return agent catalog.

export const BUILTIN_AGENTS_DATA = [
  { id: 'ui-generator', name: 'UI Generator Pro', description: 'Generates stunning UI components with glassmorphism, animations, and micro-interactions', author: 'BuildForge', version: '1.0.0', capabilities: ['ui_design', 'code_generation'], category: 'design', isPremium: false, rating: 4.8, installs: 12400, tags: ['ui', 'design', 'components', 'tailwind'], icon: '🎨' },
  { id: 'database-agent', name: 'Database Architect', description: 'Generates Prisma schemas, migrations, and CRUD operations from natural language', author: 'BuildForge', version: '1.2.0', capabilities: ['database_schema', 'api_generation'], category: 'backend', isPremium: false, rating: 4.7, installs: 8900, tags: ['database', 'prisma', 'postgresql', 'crud'], icon: '🗄️' },
  { id: 'seo-optimizer', name: 'SEO Optimizer', description: 'Adds complete SEO: meta tags, Open Graph, JSON-LD schema, sitemap, robots.txt', author: 'BuildForge', version: '1.1.0', capabilities: ['seo'], category: 'optimization', isPremium: false, rating: 4.6, installs: 7200, tags: ['seo', 'meta', 'opengraph', 'schema'], icon: '🔍' },
  { id: 'testing-agent', name: 'Test Suite Generator', description: 'Generates unit tests, integration tests, and E2E test scenarios', author: 'BuildForge', version: '1.0.0', capabilities: ['testing'], category: 'testing', isPremium: false, rating: 4.5, installs: 5600, tags: ['testing', 'jest', 'vitest', 'playwright'], icon: '🧪' },
  { id: 'analytics-agent', name: 'Analytics Integrator', description: 'Adds analytics tracking, event logging, and dashboard widgets', author: 'Community', version: '0.9.0', capabilities: ['analytics', 'code_generation'], category: 'analytics', isPremium: false, rating: 4.3, installs: 3100, tags: ['analytics', 'tracking', 'events', 'dashboard'], icon: '📊' },
  { id: 'accessibility-agent', name: 'Accessibility Auditor', description: 'Audits and fixes WCAG 2.1 AA compliance issues across all generated files', author: 'BuildForge', version: '1.0.0', capabilities: ['accessibility', 'code_generation'], category: 'optimization', isPremium: false, rating: 4.7, installs: 4800, tags: ['a11y', 'wcag', 'accessibility', 'aria'], icon: '♿' },
  { id: 'deploy-agent-pro', name: 'Deploy Agent Pro', description: 'One-click deployment to Vercel, Netlify, Railway with CI/CD pipeline setup', author: 'BuildForge', version: '2.0.0', capabilities: ['deployment'], category: 'deployment', isPremium: true, price: 2, rating: 4.9, installs: 9800, tags: ['deploy', 'vercel', 'netlify', 'cicd'], icon: '🚀' },
  { id: 'docs-generator', name: 'Documentation Generator', description: 'Auto-generates README, API docs, component storybook, and inline JSDoc comments', author: 'Community', version: '1.0.0', capabilities: ['documentation'], category: 'generation', isPremium: false, rating: 4.4, installs: 2900, tags: ['docs', 'readme', 'jsdoc', 'storybook'], icon: '📚' },
]
